# Generated by Django 3.1.2 on 2020-10-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201015_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_posts', to='posts.Tag', verbose_name='Post Tags'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='excerpt',
            field=models.TextField(blank=True, null=True, verbose_name='Tag Excerpt'),
        ),
    ]
