# Generated by Django 3.1.2 on 2020-10-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201020_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='', max_length=250, upload_to='posts/', verbose_name='Post Image'),
        ),
    ]
