# Generated by Django 3.1.2 on 2020-10-20 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201015_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='excerpt',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(verbose_name='Linkedin Social')),
                ('twitter', models.URLField(verbose_name='Linkedin Social')),
                ('facebook', models.URLField(verbose_name='Linkedin Social')),
                ('user', models.OneToOneField(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
                'db_table': 'social',
            },
        ),
    ]
