# Generated by Django 3.1.2 on 2020-10-20 01:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201020_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='excerpt',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
