# Generated by Django 3.1.2 on 2020-10-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201020_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.URLField(verbose_name='Facebook Social'),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.URLField(verbose_name='Twitter Social'),
        ),
    ]
