# Generated by Django 3.1.2 on 2020-10-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201020_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.CharField(max_length=200, verbose_name='Facebook Social'),
        ),
        migrations.AlterField(
            model_name='social',
            name='linkedin',
            field=models.CharField(max_length=200, verbose_name='Linkedin Social'),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.CharField(max_length=200, verbose_name='Twitter Social'),
        ),
    ]
